number_1 = 5
number_2 = 6
print(f'{number_1} = {bin(number_1)}')
print(f'{number_2} = {bin(number_2)}')
print(f'{number_1} & {number_2} = {number_1 & number_2} ({bin(number_1 & number_2)})')
print(f'{number_1} | {number_2} = {number_1 | number_2} ({bin(number_1 | number_2)})')
print(f'{number_1} ^ {number_2} = {number_1 ^ number_2} ({bin(number_1 ^ number_2)})')
print(f'{number_1} << 2 = {number_1 << 2} ({bin(number_1 << 2)})')
print(f'{number_1} >> 2 = {number_1 >> 2} ({bin(number_1 >> 2)})')
